### ISSUE TITLE
Is this travis failure of concern?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#299] opened 2017-10-06 16:20 UTC
https://travis-ci.org/choderalab/openmmtools/jobs/284153868#L3290-L3308
```
======================================================================
FAIL: Doctest: openmmtools.integrators.ThermostatedIntegrator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.5/doctest.py", line 2190, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for openmmtools.integrators.ThermostatedIntegrator
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/openmmtools-0.13.2-py3.5.egg/openmmtools/integrators.py", line 227, in ThermostatedIntegrator
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/openmmtools-0.13.2-py3.5.egg/openmmtools/integrators.py", line 283, in openmmtools.integrators.ThermostatedIntegrator
Failed example:
    integrator.getTemperature()
Expected:
    Traceback (most recent call last):
    ...
    AttributeError: type object 'object' has no attribute '__getattr__'
Got:
    Quantity(value=380.0, unit=kelvin)
```

**Comment by andrrizzi** [comment] 2017-10-06 16:47
Hmm, that's weird. The doctest works fine locally, and it never failed in other travis build.

**Comment by andrrizzi** [comment] 2018-03-17 00:21
Duplicate of #335.

**Closed by andrrizzi** 2018-03-17 00:21 UTC
