### ISSUE TITLE
Remove parmed dependencies for testsystems

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#224] opened 2017-06-15 15:35 UTC
Some testsystems require `parmed` instead of the `simtk.openmm.app.AmberPrmtopFile`, such as [here](https://github.com/choderalab/openmmtools/blob/master/openmmtools/testsystems.py#L3452-L3453). We should remove this requirement since openmm should have all the requisite capabilities.

cc: #223

**Comment by mjw99** [comment] 2022-05-28 14:27
./openmmtools/data/dhfr/prmtop is using the pre-AMBER 7 format, hence AmberPrmtopFile will not be able to parse it. We could update ./openmmtools/data/dhfr/{prmtop,inpcrd} to an updated AMBER 7 format?

**Comment by mjw99** [comment] 2022-05-29 14:40
Duplicate of #539

**Closed by mjw99** 2022-05-29 14:40 UTC
